### ISSUE TITLE
Error building (storybook) with v1.5.0 due to `useId`

### ISSUE THREAD

**Issue by espada-edalex** [corygibbons/react-file-icon#56]
RenovateBot opened an MR to bump the version of `react-file-icon` but the build is failing due to `React.useId`. We're using Typescript and it looks like it's complaining because that doesn't exist in out version of React (we're on `17.0.2`). 

```
ERR! [tsl] ERROR in react-frontend/node_modules/react-file-icon/dist/react-file-icon.esm.js(144,19)
ERR!       TS2339: Property 'useId' does not exist on type 'typeof React'.
ERR! Error: => Webpack failed, learn more with --debug-webpack
ERR!     at react-frontend/node_modules/@storybook/builder-webpack4/dist/cjs/index.js:249:60
ERR!     at finalCallback (portal/react-frontend/node_modules/webpack/lib/Compiler.js:257:39)
```

Has anyone else encountered this and/or have a possible workaround?

**Comment by espada-edalex** [comment]
Pretty sure this should work, but now it's throwing an error that it doesn't know the type of `useId`

```javascript
const useId = "useId" in React
  ? React.useId
  : (() => {
    let i = 0;
    return () => `${i++}`;
  })();
```

```
ERR! [tsl] ERROR in react-frontend/node_modules/react-file-icon/dist/react-file-icon.esm.js(172,12)
ERR!       TS18046: 'useId' is of type 'unknown'.
```

The actual hack I made looks like this

```javawscript
var useId = "useId" in React ? React.useId : function () {
  var i = 0;
  return function () {
    return `${i++}`;
  };
}();
```

**Comment by espada-edalex** [comment]
Pretty sure this should work, but now it's throwing an error that it doesn't know the type of `useId`

```javascript
const useId = "useId" in React
  ? React.useId
  : (() => {
    let i = 0;
    return () => `${i++}`;
  })();
```

```
ERR! [tsl] ERROR in react-frontend/node_modules/react-file-icon/dist/react-file-icon.esm.js(172,12)
ERR!       TS18046: 'useId' is of type 'unknown'.
```

The actual hack I made looks like this

```javascript
var useId = "useId" in React ? React.useId : function () {
  var i = 0;
  return function () {
    return `${i++}`;
  };
}();
```
